authorName: Long
experimentName: GAN study
trialConcurrency: 1
maxExecDuration: 24h
maxTrialNum: 20
#choice: local, remote
trainingServicePlatform: local
# searchSpacePath:
#choice: true, false
useAnnotation: true
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
trial:
  command: python dlmi.py
  codeDir: .
  gpuNum: 0